### ISSUE TITLE
[hebr/he] "No data for this character" in 3 cases

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#136]
[source] https://r12a.github.io/scripts/hebr/he

When I expand the list of 37 "cantillation" marks, the last 3 marks (each of which is arguably not a cantillation mark, BTW), say "No data for this character", as can be seen in the screen snip below:

![image](https://user-images.githubusercontent.com/941315/231454040-96342044-c7b1-4683-a9c9-560ca5c918df.png)

A separate issue is that one of these 3 "no data" code points, _qamats qatan_, is one of two doesn't belong here in this list of cantillation marks. I cover that in issue #137.

**Comment by r12a** [comment]
The 'no data' problem should now be fixed.  

Note that the intro says "many additional diacritics... **Nearly all** of the following additional marks in the Hebrew Unicode block are cantillation marks".  But i guess it wouldn't hurt to change the section title slightly.

Fix for qamats qatan still pending.

**Comment by r12a** [comment]
Section heading fixed.  And moved section further down the document, since it's not relevant to the main focus.

**Comment by bdenckla** [comment]
"No data ..." problem is indeed gone for me:

![image](https://user-images.githubusercontent.com/941315/231747838-103415f8-da8f-4a6c-bb44-e847d230f25f.png)

**Comment by bdenckla** [comment]
But these last 3 list items still have a problem, which is that they are not links like the others are. Here's a screen snip showing the last 6, allowing this contrast of link vs no-link to be seen via link coloring of the first 3:

![image](https://user-images.githubusercontent.com/941315/231748145-c88b6f66-edb6-4af2-bcfe-56aeae804826.png)

Shall I open up a separate issue, or just let this issue "morph"/expand a little to include this problem?

**Comment by r12a** [comment]
> 3 list items still have a problem, which is that they are not links like the others

Indeed, though that's actually a feature rather than a bug.  It occurs when the detailed, character by character database doesn't have a write-up for a particular character. When i add some information, the link will be activated, but until then there is nothing to link to.

No need to open a new issue, thanks.

**Comment by bdenckla** [comment]
Okay great, then nothing more to be done! Shall I close or would you prefer a workflow where you close the issue?

**Comment by r12a** [comment]
Either way works for me. So...
